language: node_js

node_js:
  - 0.8

install:
  - npm install node-static swig mocha-phantomjs

before_script:
  - git clone git://github.com/aralejs/nico-arale.git ../nico-arale
  - python ../nico-arale/spm-install.py
  - cp -r ../nico-arale/static tests/
  - mkdir tests/templates
  - cp ../nico-arale/templates/mocha-runner.html tests/templates/runner.html
  - cp ../nico-arale/test-travis.js tests/
  - nohup node tests/test-travis.js &

script: ./node_modules/.bin/mocha-phantomjs --timeout=10000 http://127.0.0.1:8000/tests/runner.html
