language: node_js

node_js:
  - 0.8

before_script:
  - git clone https://github.com/alipay/liquidluck-theme-arale2.git ../liquidluck-theme-arale2
  - cp -r ../liquidluck-theme-arale2/static tests/
  - cp -r ../liquidluck-theme-arale2/templates tests/
  - cp -r ../liquidluck-theme-arale2/test-travis.js tests/
  - nohup node tests/test-travis.js &

install: 
  - git clone https://github.com/seajs/spm.git ../spm
  - npm install ../spm
  - npm install node-static swig phantomjs 
  - spm env --init
  - sed -i 's/\[/[\"modules.aralejs.org\",/g' ~/.spm/config.json
  - spm install

script: ./node_modules/.bin/phantomjs tests/static/js/run_jasmine_test.coffee http://127.0.0.1:8000/tests/runner.html
